# task_002_3d_model_system.yaml
# 3Dモデル管理システム実装
# 作成日: 2025-08-04

# ── 基本情報 ─────────────────────────────
task_id: 002
title: "3Dモデル管理システム実装"
parent_task_id: null
status: backlog
priority: 1
tags: ["3d", "scenekit", "models", "core"]

# ── 進捗管理 ─────────────────────────────
progress:
  completed_steps: []
  current_step: 1
  blockers: []
  notes: ""

# ── 必要素材 ───────────────────────────
inputs:
  - title: "プロジェクト初期設定"
    status: pending
    description: "task_001の完了"
    items: ["task_001_project_setup.yaml"]
    required: true
  - title: "iPhone OBJモデル"
    status: absent
    description: "iPhone 12-15のOBJファイル"
    items: ["iphone12.obj", "iphone13.obj", "iphone14.obj", "iphone15.obj"]
    required: true
  - title: "SceneKit知識"
    status: present
    description: "SceneKit開発経験またはドキュメント"
    items: ["SceneKit Documentation"]
    required: true

# ── 期待成果物 ─────────────────────────
outputs:
  - title: "3Dモデル管理クラス"
    status: pending
    items: ["Sources/Services/ModelManager.swift"]
  - title: "SceneKit表示View"
    status: pending
    items: ["Sources/Views/SceneView.swift"]
  - title: "モデルアセット"
    status: pending
    items: ["Resources/Models/"]
  - title: "単体テスト"
    status: pending
    items: ["Tests/Unit/ModelManagerTests.swift"]

# ── 実装ステップ ───────────────────────
steps:
  - number: 1
    title: "OBJモデルファイル準備"
    description: |
      iPhone 3Dモデルファイルの準備と配置:
      - iPhone 12, 13, 14, 15のOBJファイル取得
      - Resources/Models/フォルダに配置
      - Xcodeプロジェクトにリソースとして追加
      - ファイルサイズとポリゴン数の最適化確認
    estimated_time: 60
    dependencies: []
    files_to_modify: ["Resources/Models/", "AppMock3D.xcodeproj"]
    acceptance_criteria: "全OBJファイルがプロジェクトに正しく追加され、読み込み可能"

  - number: 2
    title: "DeviceModel構造体作成"
    description: |
      デバイスモデル情報を管理する構造体:
      - デバイス名、OBJファイルパス、画面サイズ情報
      - デバイス一覧の定義
      - Codableプロトコル対応（設定保存用）
    estimated_time: 30
    dependencies: [1]
    files_to_modify: ["Sources/Models/DeviceModel.swift"]
    acceptance_criteria: "DeviceModel構造体が定義され、全対応デバイス情報が含まれる"

  - number: 3
    title: "ModelManager作成"
    description: |
      3Dモデルの読み込み・管理を行うクラス:
      - OBJファイルの読み込み機能
      - SCNNodeの生成と管理
      - モデル切り替え機能
      - エラーハンドリング
      - メモリ管理（未使用モデルの解放）
    estimated_time: 120
    dependencies: [2]
    files_to_modify: ["Sources/Services/ModelManager.swift"]
    acceptance_criteria: "OBJファイルからSCNNodeを生成し、適切に管理できる"

  - number: 4
    title: "SceneView作成"
    description: |
      SwiftUIでSceneKitを表示するView:
      - SCNViewのSwiftUIラッパー
      - カメラ設定（初期位置・角度）
      - ライティング設定
      - 背景設定（透明/単色/グラデーション対応）
      - UIViewRepresentable実装
    estimated_time: 90
    dependencies: [3]
    files_to_modify: ["Sources/Views/SceneView.swift"]
    acceptance_criteria: "SwiftUIアプリ内でSceneKitシーンが正しく表示される"

  - number: 5
    title: "環境ライティング実装"
    description: |
      3Dシーンの照明システム:
      - 環境光の設定（intensity調整可能）
      - ディレクショナルライト
      - 影の設定
      - リアルタイム調整機能
    estimated_time: 60
    dependencies: [4]
    files_to_modify: ["Sources/Services/LightingManager.swift"]
    acceptance_criteria: "適切な照明でiPhoneモデルが美しく表示される"

  - number: 6
    title: "単体テスト作成"
    description: |
      ModelManagerとSceneViewの単体テスト:
      - OBJファイル読み込みテスト
      - モデル切り替えテスト
      - エラーハンドリングテスト
      - メモリリークテスト
    estimated_time: 75
    dependencies: [5]
    files_to_modify: ["Tests/Unit/ModelManagerTests.swift", "Tests/Unit/SceneViewTests.swift"]
    acceptance_criteria: "全テストが成功し、80%以上のコードカバレッジ"

  - number: 7
    title: "パフォーマンステスト"
    description: |
      3D描画パフォーマンスの確認:
      - FPS測定（目標60fps）
      - メモリ使用量測定
      - モデル切り替え時の性能測定
      - 低スペックデバイスでの動作確認
    estimated_time: 45
    dependencies: [6]
    files_to_modify: []
    acceptance_criteria: "iPhone 12以降で60fps、メモリ使用量が基準内"

# ── メタデータ ─────────────────────────────
created_at: 2025-08-04T15:00:00+09:00
updated_at: 2025-08-04T15:00:00+09:00