# task_003_basic_ui.yaml
# 基本UI構築
# 作成日: 2025-08-04

# ── 基本情報 ─────────────────────────────
task_id: 003
title: "基本UI構築"
parent_task_id: null
status: done
priority: 1
tags: ["ui", "swiftui", "design", "navigation"]

# ── 進捗管理 ─────────────────────────────
progress:
  completed_steps: [1, 2, 3, 4, 5, 6, 7, 8]
  current_step: 8
  blockers: []
  notes: "AppBarViewとBottomNavViewを作成し、ContentViewに統合しました。PreviewAreaViewも実装し、基本的なUIテストも作成しました。"

# ── 必要素材 ───────────────────────────
inputs:
  - title: "プロジェクト初期設定"
    status: pending
    description: "task_001の完了"
    items: ["task_001_project_setup.yaml"]
    required: true
  - title: "3Dシーン表示機能"
    status: pending
    description: "task_002の完了"
    items: ["task_002_3d_model_system.yaml"]
    required: true
  - title: "UI仕様書"
    status: present
    description: "spec.yamlのUI仕様"
    items: ["spec.yaml#user_interface"]
    required: true
  - title: "アイコンアセット"
    status: absent
    description: "アプリ用アイコンファイル"
    items: ["ic_save.png", "ic_settings.png", "ic_move.png", "ic_scale.png", "ic_rotate.png"]
    required: false

# ── 期待成果物 ─────────────────────────
outputs:
  - title: "メイン画面View"
    status: pending
    items: ["Sources/Views/ContentView.swift"]
  - title: "アプリバーView"
    status: pending
    items: ["Sources/Views/AppBarView.swift"]
  - title: "ボトムナビゲーションView"
    status: pending
    items: ["Sources/Views/BottomNavView.swift"]
  - title: "UIテスト"
    status: pending
    items: ["Tests/UI/BasicUITests.swift"]

# ── 実装ステップ ───────────────────────
steps:
  - number: 1
    title: "アイコンアセット準備"
    description: |
      アプリで使用するアイコンの準備:
      - SF Symbolsの使用を優先
      - カスタムアイコンが必要な場合は準備
      - Assets.xcassetsに追加
      - ダークモード対応確認
    estimated_time: 30
    dependencies: []
    files_to_modify: ["Assets.xcassets"]
    acceptance_criteria: "全必要アイコンがアセットに追加され、ライト・ダークモードで表示確認"

  - number: 2
    title: "AppBarView作成"
    description: |
      上部アプリバーの実装:
      - 高さ56pt、背景色#FFFFFF
      - elevation効果（影）
      - 保存ボタン（ic_save）
      - 設定ボタン（ic_settings）
      - タイトル表示
    estimated_time: 45
    dependencies: [1]
    files_to_modify: ["Sources/Views/AppBarView.swift"]
    acceptance_criteria: "アプリバーが仕様通りに表示され、ボタンタップが反応する"

  - number: 3
    title: "BottomNavView作成"
    description: |
      下部ナビゲーションバーの実装:
      - 高さ72pt、背景色#FFFFFF
      - elevation効果（影）
      - 6つのナビゲーションアイコン
      - 選択状態の表示
      - ツールチップ表示
    estimated_time: 60
    dependencies: [1]
    files_to_modify: ["Sources/Views/BottomNavView.swift"]
    acceptance_criteria: "ボトムナビが仕様通りに表示され、選択状態が正しく管理される"

  - number: 4
    title: "メイン画面レイアウト"
    description: |
      ContentViewのレイアウト構築:
      - VStackでAppBar、3Dプレビューエリア、BottomNavを配置
      - 3Dプレビューエリアをflexible設定
      - Safe Areaの適切な処理
      - 画面回転対応
    estimated_time: 90
    dependencies: [2, 3]
    files_to_modify: ["Sources/Views/ContentView.swift"]
    acceptance_criteria: "メイン画面が正しくレイアウトされ、画面回転に対応"

  - number: 5
    title: "プレビューエリア実装"
    description: |
      3Dモデル表示エリアの実装:
      - SceneViewの統合
      - マスクエリア外の暗転表示（#000000, opacity 0.5）
      - ビューポート境界線表示（#FFFFFF, 2pt）
      - ジェスチャー領域の設定
    estimated_time: 75
    dependencies: [4]
    files_to_modify: ["Sources/Views/PreviewAreaView.swift"]
    acceptance_criteria: "3Dシーンが適切にマスクされ、境界線が表示される"

  - number: 6
    title: "状態管理実装"
    description: |
      アプリの状態管理システム:
      - 操作モード管理（移動、拡大縮小、回転等）
      - 設定値の管理
      - ObservableObjectクラス作成
      - @StateObject / @ObservedObjectの適切な使用
    estimated_time: 60
    dependencies: [5]
    files_to_modify: ["Sources/Models/AppState.swift"]
    acceptance_criteria: "アプリ状態が適切に管理され、UI更新が正しく反映される"

  - number: 7
    title: "UIテスト作成"
    description: |
      基本UIの自動テスト:
      - アプリ起動テスト
      - ナビゲーション動作テスト
      - ボタンタップ反応テスト
      - 画面回転テスト
    estimated_time: 90
    dependencies: [6]
    files_to_modify: ["Tests/UI/BasicUITests.swift"]
    acceptance_criteria: "全UIテストが成功し、基本動作が保証される"

  - number: 8
    title: "レスポンシブデザイン確認"
    description: |  
      異なる画面サイズでの表示確認:
      - iPhone mini, standard, Plus, Pro Max対応
      - iPadでの表示確認（将来対応予定）
      - セーフエリアの適切な処理確認
      - アクセシビリティ対応確認
    estimated_time: 45
    dependencies: [7]
    files_to_modify: []
    acceptance_criteria: "全対象デバイスで適切にレイアウトされ、アクセシビリティ基準を満たす"

# ── メタデータ ─────────────────────────────
created_at: 2025-08-04T15:00:00+09:00
updated_at: 2025-08-04T15:00:00+09:00