# task_007_settings_ui.yaml
# 設定画面・機能実装
# 作成日: 2025-08-04

# ── 基本情報 ─────────────────────────────
task_id: 007
title: "設定画面・機能実装"
parent_task_id: null
status: done
priority: 3
tags: ["settings", "ui", "configuration", "bottomsheet"]

# ── 進捗管理 ─────────────────────────────
progress:
  completed_steps: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  current_step: 0
  blockers: []
  notes: "設定データモデル、ボトムシート基盤、各種設定UIが完成しました。単体テストとUIテストが完成しました。タスクは完了しました。"

# ── 必要素材 ───────────────────────────
inputs:
  - title: "基本UI"
    status: pending
    description: "task_003の完了"
    items: ["task_003_basic_ui.yaml"]
    required: true
  - title: "エクスポート機能"
    status: pending
    description: "task_006の完了"
    items: ["task_006_export_system.yaml"]
    required: true
  - title: "設定仕様"
    status: present
    description: "spec.yamlの設定要件"
    items: ["spec.yaml#configuration_options"]
    required: true
  - title: "インタラクション仕様"
    status: present
    description: "spec.yamlのインタラクション仕様"
    items: ["spec.yaml#user_interface.interaction_modes"]
    required: true

# ── 期待成果物 ─────────────────────────
outputs:
  - title: "設定データモデル"
    status: pending
    items: ["Sources/Models/AppSettings.swift"]
  - title: "アスペクト比設定UI"
    status: pending
    items: ["Sources/Views/AspectRatioSettingsView.swift"]
  - title: "背景設定UI"
    status: pending
    items: ["Sources/Views/BackgroundSettingsView.swift"]
  - title: "デバイス選択UI"
    status: pending
    items: ["Sources/Views/DeviceSelectionView.swift"]
  - title: "ボトムシート管理"
    status: pending
    items: ["Sources/Views/BottomSheetManager.swift"]
  - title: "単体テスト"
    status: pending
    items: ["Tests/Unit/SettingsTests.swift"]

# ── 実装ステップ ───────────────────────
steps:
  - number: 1
    title: "設定データモデル作成"
    description: |
      アプリ設定を管理するデータモデル:
      - AppSettings構造体（Codable対応）
      - アスペクト比設定（プリセット・カスタム）
      - 寸法設定（幅・高さ・制限）
      - 背景設定（単色・透明・グラデーション）
      - 環境ライティング設定
      - デバイスモデル選択
    estimated_time: 60
    dependencies: []
    files_to_modify: ["Sources/Models/AppSettings.swift"]
    acceptance_criteria: "全設定項目がモデル化され、UserDefaultsで永続化される"

  - number: 2
    title: "ボトムシート基盤システム"
    description: |
      設定表示用ボトムシートの基盤:
      - SwiftUIでのボトムシート実装
      - ドラッグジェスチャー対応
      - 高さ調整機能
      - アニメーション設定
      - 背景オーバーレイ
    estimated_time: 90
    dependencies: [1]
    files_to_modify: ["Sources/Views/BottomSheetManager.swift"]
    acceptance_criteria: "滑らかなアニメーションでボトムシートが表示・非表示される"

  - number: 3
    title: "アスペクト比設定画面"
    description: |
      アスペクト比設定のUI実装:
      - プリセット選択（16:9, 4:3, 1:1, 3:4, 9:16）
      - カスタムアスペクト比入力（0.1〜10.0）
      - リアルタイムプレビュー
      - 縦横比維持設定
      - 数値入力バリデーション
    estimated_time: 75
    dependencies: [2]
    files_to_modify: ["Sources/Views/AspectRatioSettingsView.swift"]
    acceptance_criteria: "アスペクト比の変更が即座に3Dプレビューに反映される"

  - number: 4
    title: "寸法設定機能"
    description: |
      出力画像寸法の設定機能:
      - 幅・高さの個別設定（100〜4096px）
      - アスペクト比連動機能
      - プリセット寸法（1080p, 4K等）
      - 入力値の即座反映
      - 制限値の警告表示
    estimated_time: 60
    dependencies: [3]
    files_to_modify: ["Sources/Views/DimensionsSettingsView.swift"]
    acceptance_criteria: "寸法設定が適切に管理され、制限値を超える場合に警告が表示される"

  - number: 5
    title: "背景設定画面"
    description: |
      背景設定のUI実装:
      - 単色背景（カラーピッカー）
      - 透明背景切り替え
      - グラデーション設定（線形・放射状）
      - グラデーション色選択
      - リアルタイムプレビュー
    estimated_time: 105
    dependencies: [2]
    files_to_modify: ["Sources/Views/BackgroundSettingsView.swift"]
    acceptance_criteria: "すべての背景オプションが設定でき、即座にプレビューに反映される"

  - number: 6
    title: "環境ライティング設定"
    description: |
      3Dシーンの照明設定UI:
      - ライト強度スライダー（0.0〜2.0）
      - リアルタイム調整
      - プリセット照明設定
      - 照明プレビュー
      - デフォルト値リセット機能
    estimated_time: 45
    dependencies: [2]
    files_to_modify: ["Sources/Views/LightingSettingsView.swift"]
    acceptance_criteria: "照明設定がリアルタイムで3Dモデルに反映される"

  - number: 7
    title: "デバイス選択画面"
    description: |
      iPhone機種選択のUI実装:
      - 対応機種一覧表示（iPhone 12-15）
      - デバイス画像プレビュー
      - 選択デバイスの即座切り替え
      - 機種情報の表示
      - お気に入り機種設定
    estimated_time: 75
    dependencies: [2]
    files_to_modify: ["Sources/Views/DeviceSelectionView.swift"]
    acceptance_criteria: "デバイス選択が正しく動作し、3Dモデルが切り替わる"

  - number: 8
    title: "設定統合とナビゲーション"
    description: |
      ボトムナビゲーションとの統合:
      - 各設定画面の表示切り替え
      - 設定変更の即座反映
      - 設定リセット機能
      - 設定の自動保存
      - エラーハンドリング
    estimated_time: 60
    dependencies: [3, 4, 5, 6, 7]
    files_to_modify: ["Sources/Views/SettingsCoordinator.swift"]
    acceptance_criteria: "ボトムナビゲーションから各設定画面にアクセスでき、設定が正しく保存される"

  - number: 9
    title: "単体テスト作成"
    description: |
      設定機能のテスト:
      - 設定値の保存・読み込みテスト
      - バリデーション機能テスト
      - UI状態管理テスト
      - 設定変更反映テスト
      - エラーハンドリングテスト
    estimated_time: 90
    dependencies: [8]
    files_to_modify: ["Tests/Unit/SettingsTests.swift"]
    acceptance_criteria: "設定機能の全機能が正しく動作することがテストで保証される"

  - number: 10
    title: "UIテスト作成"
    description: |
      設定画面のUIテスト:
      - ボトムシート表示・非表示テスト
      - 各設定画面の操作テスト
      - 設定値変更の反映テスト
      - アクセシビリティテスト
    estimated_time: 75
    dependencies: [9]
    files_to_modify: ["Tests/UI/SettingsUITests.swift"]
    acceptance_criteria: "設定画面の全UI操作が自動テストで検証される"

# ── メタデータ ─────────────────────────────
created_at: 2025-08-04T15:00:00+09:00
updated_at: 2025-08-04T15:00:00+09:00